// <auto-generated />
using System;
using CapitolFarmsProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CapitolFarmsProject.Migrations
{
    [DbContext(typeof(CapitolFarmsProjectContext))]
    [Migration("20180809184441_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("CapitolFarmsProject.Models.Grain", b =>
                {
                    b.Property<int>("GrainId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GrainName");

                    b.HasKey("GrainId");

                    b.ToTable("Grain");
                });

            modelBuilder.Entity("CapitolFarmsProject.Models.Horse", b =>
                {
                    b.Property<int>("HorseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HorseName");

                    b.Property<int>("Location");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo");

                    b.HasKey("HorseId");

                    b.ToTable("Horse");
                });

            modelBuilder.Entity("CapitolFarmsProject.Models.HorseGrain", b =>
                {
                    b.Property<int>("HorseGrainId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<int?>("GrainId");

                    b.Property<int?>("HorseId");

                    b.Property<int>("ReportTime");

                    b.HasKey("HorseGrainId");

                    b.HasIndex("GrainId");

                    b.HasIndex("HorseId");

                    b.ToTable("HorseGrain");
                });

            modelBuilder.Entity("CapitolFarmsProject.Models.HorseGrain", b =>
                {
                    b.HasOne("CapitolFarmsProject.Models.Grain", "Grain")
                        .WithMany("HorseGrains")
                        .HasForeignKey("GrainId");

                    b.HasOne("CapitolFarmsProject.Models.Horse", "Horse")
                        .WithMany("HorseGrains")
                        .HasForeignKey("HorseId");
                });
#pragma warning restore 612, 618
        }
    }
}
